# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fLhdcV5VQ7vHXofTCsR3WAU2vLFTIbUR
"""

import pandas as pd
import numpy as np

df = pd.read_csv("w1_student_scores.csv")

df.head()

from matplotlib import pyplot as plt
plt.figure(figsize=(6,4))
plt.plot(df['Hours'],df['Scores'],'ro')
plt.title('Student Score vs Hours Studied')
plt.xlabel('Hours')
plt.ylabel('Scores')

plt.show()

"""**Find Coefficient**

calculate the mean of input and output
"""

xmean = np.mean(df['Hours'])
ymean = np.mean(df['Scores'])

df['xycov'] = (df['Hours']- xmean) * (df['Scores']-ymean)
df['xvar'] = (df['Hours']- xmean)**2

slope = df['xycov'].sum()/ df['xvar'].sum()

intercept = ymean - (slope * xmean)

print(f'slope = {slope}')
print(f'intercept = {intercept}')

intercept + slope*7

Scores_predicted = intercept + slope * df['Hours']

plt.figure(figsize=(6,4))
plt.plot(df['Hours'],Scores_predicted)
plt.plot(df['Hours'],df['Scores'],'ro')
# plt.plot(df['Hours'],df['Scores'])

plt.title('Actual vs Predicted')
plt.xlabel('Hours')
plt.ylabel('Scores')

plt.show()